<header>

<div>
    <img src="{{ Vite::asset('resources/img/dc-logo.png') }}" alt="">
    <ul>            
            <li>
                Characters
            </li>
            <li>
                Comics
            </li>
            <li>
               Movies
            </li>
            <li>
                TV
            </li>
            <li>
                Videos
            </li>
            <li>
                Games
            </li>
            <li>
                News
            </li>            
        </ul>
    </div>
</header>